package com.huateng.p3.account.inner;

import java.util.Date;

import org.junit.Test;
import org.springframework.beans.factory.annotation.Autowired;

import base.BaseAccountServiceSpringTest;

import com.huateng.p3.account.common.bizparammodel.PaymentInfo;
import com.huateng.p3.account.common.bizparammodel.TxnResultObject;
import com.huateng.p3.account.common.enummodel.KeyType;
import com.huateng.p3.account.common.enummodel.TxnForm;
import com.huateng.p3.account.common.enummodel.TxnType;
import com.huateng.p3.account.commonservice.AccountService;
import com.huateng.p3.account.persistence.TInfoAccountMapper;
import com.huateng.p3.account.persistence.models.TInfoAccount;
import com.huateng.p3.account.persistence.models.TInfoCustomer;
import com.huateng.p3.account.persistence.models.TInfoOrg;
import com.huateng.p3.account.persistence.models.TLogOnlinePayment;

/**
 * Created with IntelliJ IDEA.
 * User: Administrator
 * Date: 13-12-23
 * Time: 上午9:19
 * To change this template use File | Settings | File Templates.
 */
public class AccountServiceTest extends BaseAccountServiceSpringTest {

    @Autowired
    private AccountService service;

    @Test
    public void testgetAccountForUpdate(){
        String customerNo = "8630898000000322";
        KeyType keyType = KeyType.CUSTOMER;
        TInfoAccount infoAccount = service.getAccountForUpdate(customerNo,keyType);
        System.out.println("------testgetAccountForUpdate获得txn_password:----------"+ infoAccount.getPayPasswd());
    }
    @Test
    public void testgetAccount(){
        String accountKey = "8631898000000323";
        KeyType keyType = KeyType.ACCOUNT;
        TInfoAccount infoAccount = service.getAccount(accountKey, keyType);
        System.out.println("------testgetAccount获得txn_password:----------"+ infoAccount.getPayPasswd());
    }

    @Test
    public void testincreaseTxnPasswdErrorNum(){
        TInfoAccount account= new TInfoAccount();
        account.setAccountNo("8631898000000323");
        account.setPasswdErrNum(2L);
        account.setPasswdErrLockTime(new Date());
        String txnTyp =""; // 这参数貌似没用，需要密力确认
        int i = service.increaseTxnPasswdErrorNum(account);
        System.out.println("------testincreaseTxnPasswdErrorNum 返回修改状态:----------"+ i);
    }

    @Test
    public void testgetTInfoAccountMapper(){
        TInfoAccountMapper mapper = service.getTInfoAccountMapper();
        System.out.println("mapper ==null :"+mapper == null);
    }

    @Test
    public void testaccountClearInDb(){
        TInfoOrg supplyOrg = new TInfoOrg();
        String s = "s";
        Long l = 11L;
        Date date = new Date();
        supplyOrg.setRecordNo(l);
        supplyOrg.setOrgCode(s);
        supplyOrg.setOrgType(s);
        supplyOrg.setSubType(s);
        supplyOrg.setOrgFname(s);
        supplyOrg.setOrgSname(s);
        supplyOrg.setIndustryType(s);
        supplyOrg.setAddress(s);
        supplyOrg.setZipCode(s);
        supplyOrg.setBusinessLicenseNo(s);
        supplyOrg.setOrganizationCode(s);
        supplyOrg.setLegalRepresentiveName(s);
        supplyOrg.setLinkmanName(s);
        supplyOrg.setLinkmanTelephone(s);
        supplyOrg.setLinkmanFax(s);
        supplyOrg.setLinkmanEmail(s);
        supplyOrg.setServiceLevel(s);
        supplyOrg.setRiskLevel(s);
        supplyOrg.setAllowTrans(s);
        supplyOrg.setOrgStatus(s);
        supplyOrg.setAreaCode(s);
        supplyOrg.setCityCode(s);
        supplyOrg.setUpOrgCode(s);
        supplyOrg.setSignOrgCode(s);
        supplyOrg.setClearingOrgCode(s);
        supplyOrg.setSettlementOrgCode(s);
        supplyOrg.setSettlementMode(s);
        supplyOrg.setIsRealClear(s);
        supplyOrg.setClearingDate(s);
        supplyOrg.setSettleDate(s);
        supplyOrg.setfLinkmanName(s);
        supplyOrg.setfLinkmanTelephone(s);
        supplyOrg.setfLinkmanFax(s);
        supplyOrg.setfLinkmanEmail(s);
        supplyOrg.setCreateUid(s);
        supplyOrg.setCreateTime(date);
        supplyOrg.setCheckFlag(s);
        supplyOrg.setCheckUid(s);
        supplyOrg.setCheckTime(date);
        supplyOrg.setLastModifyUid(s);
        supplyOrg.setLastModifyTime(date);
        supplyOrg.setSettlementMin1(l);
        supplyOrg.setSettlementMin2(l);
        supplyOrg.setSettlementMin3(l);
        supplyOrg.setSettlementMin4(l);
        supplyOrg.setSettlementMin5(l);
        supplyOrg.setChargeAccFlag(s);
        supplyOrg.setOrgKind(s);
        supplyOrg.setArchiveTime(date);
        supplyOrg.setArchiveFlag(s);
        supplyOrg.setlRecordNo(l);
        supplyOrg.setRemark(s);
        supplyOrg.setBlackLabel(s);
        supplyOrg.setSettleFlag(s);
        supplyOrg.setPayType(s);
        supplyOrg.setResvFld1(s);
        supplyOrg.setResvFld2(s);
        supplyOrg.setResvFld3(s);
        TInfoOrg acceptOrg = new TInfoOrg();
        acceptOrg.setRecordNo(l);
        acceptOrg.setOrgCode(s);
        acceptOrg.setOrgType(s);
        acceptOrg.setSubType(s);
        acceptOrg.setOrgFname(s);
        acceptOrg.setOrgSname(s);
        acceptOrg.setIndustryType(s);
        acceptOrg.setAddress(s);
        acceptOrg.setZipCode(s);
        acceptOrg.setBusinessLicenseNo(s);
        acceptOrg.setOrganizationCode(s);
        acceptOrg.setLegalRepresentiveName(s);
        acceptOrg.setLinkmanName(s);
        acceptOrg.setLinkmanTelephone(s);
        acceptOrg.setLinkmanFax(s);
        acceptOrg.setLinkmanEmail(s);
        acceptOrg.setServiceLevel(s);
        acceptOrg.setRiskLevel(s);
        acceptOrg.setAllowTrans(s);
        acceptOrg.setOrgStatus(s);
        acceptOrg.setAreaCode(s);
        acceptOrg.setCityCode(s);
        acceptOrg.setUpOrgCode(s);
        acceptOrg.setSignOrgCode(s);
        acceptOrg.setClearingOrgCode(s);
        acceptOrg.setSettlementOrgCode(s);
        acceptOrg.setSettlementMode(s);
        acceptOrg.setIsRealClear(s);
        acceptOrg.setClearingDate(s);
        acceptOrg.setSettleDate(s);
        acceptOrg.setfLinkmanName(s);
        acceptOrg.setfLinkmanTelephone(s);
        acceptOrg.setfLinkmanFax(s);
        acceptOrg.setfLinkmanEmail(s);
        acceptOrg.setCreateUid(s);
        acceptOrg.setCreateTime(date);
        acceptOrg.setCheckFlag(s);
        acceptOrg.setCheckUid(s);
        acceptOrg.setCheckTime(date);
        acceptOrg.setLastModifyUid(s);
        acceptOrg.setLastModifyTime(date);
        acceptOrg.setSettlementMin1(l);
        acceptOrg.setSettlementMin2(l);
        acceptOrg.setSettlementMin3(l);
        acceptOrg.setSettlementMin4(l);
        acceptOrg.setSettlementMin5(l);
        acceptOrg.setChargeAccFlag(s);
        acceptOrg.setOrgKind(s);
        acceptOrg.setArchiveTime(date);
        acceptOrg.setArchiveFlag(s);
        acceptOrg.setlRecordNo(l);
        acceptOrg.setRemark(s);
        acceptOrg.setBlackLabel(s);
        acceptOrg.setSettleFlag(s);
        acceptOrg.setPayType(s);
        acceptOrg.setResvFld1(s);
        acceptOrg.setResvFld2(s);
        acceptOrg.setResvFld3(s);
        PaymentInfo paymentInfo = new PaymentInfo();
       

        paymentInfo.setMerchantCode(s);
        paymentInfo.setSupplyOrgCode(s);
        paymentInfo.setChannel(s);
        paymentInfo.setBussinessType(s);
        paymentInfo.setInnerTxnType(s);
        paymentInfo.setAmount(l);
        paymentInfo.setTerminalNo(s);
        paymentInfo.setTerminalSeqNo(s);
        paymentInfo.setAcceptOrgCode(s);
        paymentInfo.setAcceptTxnSeqNo(s);
        paymentInfo.setAcceptOperatorNo(s);
        paymentInfo.setAcceptDate(s);
        paymentInfo.setAcceptTime(s);
        paymentInfo.setPayOrgCode(s);
        paymentInfo.setTxnType(TxnType.TXN_CONSUME);
        paymentInfo.setTxnDscpt(s);


        PaymentInfo oldPaymentInfo = new PaymentInfo();
        oldPaymentInfo.setMerchantCode(s);
        oldPaymentInfo.setSupplyOrgCode(s);
        oldPaymentInfo.setChannel(s);
        oldPaymentInfo.setBussinessType(s);
        oldPaymentInfo.setInnerTxnType(s);
        oldPaymentInfo.setAmount(l);
        oldPaymentInfo.setTerminalNo(s);
        oldPaymentInfo.setTerminalSeqNo(s);
        oldPaymentInfo.setAcceptOrgCode(s);
        oldPaymentInfo.setAcceptTxnSeqNo(s);
        oldPaymentInfo.setAcceptOperatorNo(s);
        oldPaymentInfo.setAcceptDate(s);
        oldPaymentInfo.setAcceptTime(s);
        oldPaymentInfo.setPayOrgCode(s);
        oldPaymentInfo.setTxnType(TxnType.TXN_CONSUME);
        oldPaymentInfo.setTxnDscpt(s);



        TInfoCustomer tInfoCustomer = new TInfoCustomer();
        tInfoCustomer.setCustomerNo(s);
        tInfoCustomer.setUnifyId(s);
        tInfoCustomer.setIsRealname(s);
        tInfoCustomer.setName(s);
        tInfoCustomer.setIsRequestCertificate(s);
        tInfoCustomer.setRegisterType(s);
        tInfoCustomer.setMobileNo(s);
        tInfoCustomer.setEmailAddress(s);
        tInfoCustomer.setUserName(s);
        tInfoCustomer.setNickName(s);
        tInfoCustomer.setWebLoginPassword(s);
        tInfoCustomer.setIvrPassword(s);
        tInfoCustomer.setAccountQueryPassword(s);
        tInfoCustomer.setGender(s);
        tInfoCustomer.setIdentifyType(s);
        tInfoCustomer.setIdentifyNo(s);
        tInfoCustomer.setHomeTelephone(s);
        tInfoCustomer.setOfficeTelephone(s);
        tInfoCustomer.setOtherTelephone(s);
        tInfoCustomer.setApanage(s);
        tInfoCustomer.setAreaCode(s);
        tInfoCustomer.setCityCode(s);
        tInfoCustomer.setContactAddress(s);
        tInfoCustomer.setContactZipcode(s);
        tInfoCustomer.setOrganizationAddress(s);
        tInfoCustomer.setOrganizationZipcode(s);
        tInfoCustomer.setPwdErrCount(l);
        tInfoCustomer.setLockTimeLimit(date);
        tInfoCustomer.setOrganizationCode(s);
        tInfoCustomer.setQuestion(s);
        tInfoCustomer.setAnswer(s);
        tInfoCustomer.setActiveAddress(s);
        tInfoCustomer.setActiveCode(s);
        tInfoCustomer.setActiveStatus(s);
        tInfoCustomer.setRegisteDate(date);
        tInfoCustomer.setIsClosingAccount(s);
        tInfoCustomer.setRegisteOrgCode(s);
        tInfoCustomer.setRegisteUid(s);
        tInfoCustomer.setManager(s);
        tInfoCustomer.setLastSuccessLoginTime(date);
        tInfoCustomer.setLastSuccessLoginIp(s);
        tInfoCustomer.setLastFailLoginTime(date);
        tInfoCustomer.setLastFailLoginIp(s);
        tInfoCustomer.setLastUpdateTime(date);
        tInfoCustomer.setCustomerStatus(s);
        tInfoCustomer.setCloseTime(date);
        tInfoCustomer.setActiveTimeLimit(date);
        tInfoCustomer.setActiveTime(date);
        tInfoCustomer.setCustomerGrade(s);
        tInfoCustomer.setCustomerType(s);
        tInfoCustomer.setNationality(s);
        tInfoCustomer.setProfession(s);
        tInfoCustomer.setIdentifyExpiredDate(s);
        tInfoCustomer.setBlacklistFlag(s);



        TInfoAccount account = new TInfoAccount();
        account.setAccountNo(s);
        account.setAccountName(s);
        account.setCustomerNo(s);
        account.setOpenDate(date);
        account.setCloseDate(date);
        account.setExpiredDate(date);
        account.setPayPasswd(s);
        account.setInitPasswd(s);
        account.setInitPasswdModified(s);
        account.setPasswdErrNum(l);
        account.setPasswdErrLockTime(date);
        account.setStatus(s);
        account.setCommStatus(s);
        account.setType(s);
        account.setGrade(s);
        account.setIsRealname(s);
        account.setApanage(s);
        account.setOrganizationCode(s);
        account.setAreaCode(s);
        account.setCityCode(s);
        account.setOpenChannel(s);
        account.setBalance(l);
        account.setLastDayBal(l);
        account.setLastMonthBal(l);
        account.setAvailableBalance(l);
        account.setUnavailableBalance(l);
        account.setWithdrawBalance(l);
        account.setFrozenAmount(l);
        account.setPreauthorizedAmt(l);
        account.setLastTxnDate(s);
        account.setDaySumConsAmt(l);
        account.setDaySumConsCnt(1);
        account.setDaySumOutAmt(l);
        account.setDaySumOutCnt(1);
        account.setDaySumInAmt(l);
        account.setDaySumInCnt(1);
        account.setDaySumCashAmt(l);
        account.setDaySumCashCnt(1);
        account.setDaySumDepositAmt(l);
        account.setDaySumDepositCnt(1);
        account.setMonthSumConsAmt(l);
        account.setMonthSumOutAmt(l);
        account.setMonthSumInAmt(l);
        account.setMonthSumCashAmt(l);
        account.setMonthSumChgAmt(l);
        account.setIsAllowedClose(s);
        account.setIsCloseRtnCash(s);
        account.setEncryptedMsg(s);
        account.setLastUpdateTime(date);
        account.setLastTxnTime(date);
        account.setRsvdAmt1(l);
        account.setRsvdAmt2(l);
        account.setRsvdText1(s);
        account.setRsvdText2(s);
        account.setMonthSumConsCnt(l);
        account.setMonthSumOutCnt(l);
        account.setMonthSumInCnt(l);
        account.setMonthSumCashCnt(l);
        account.setMonthSumChgCnt(l);
        account.setMasterAccountNo(s);
        account.setForbiddenTxn(s);
        account.setExtendCount(l);
        account.setForbiddenChannel(s);
        account.setCardNo(s);
        account.setCardType(s);
        account.setCardBindingMethod(s);

        String oldOnlineTxnSeqNo = oldPaymentInfo.getAcceptTxnSeqNo();
        String isClearing = "";
        String isrollback = "";
        TLogOnlinePayment tLogOnlinePayment = service.accountClearInDb(supplyOrg,acceptOrg,paymentInfo,oldPaymentInfo,tInfoCustomer,account,oldOnlineTxnSeqNo,isClearing,isrollback);

        System.out.println("测试返回结果："+tLogOnlinePayment.getAccountNo());
    }

    @Test
    public void accounTxnInDb(){
        String s = "s";
        Long l = 11L;
        Date date = new Date();

        PaymentInfo paymentInfo = new PaymentInfo();

        paymentInfo.setMerchantCode(s);
        paymentInfo.setSupplyOrgCode(s);
        paymentInfo.setChannel(s);
        paymentInfo.setBussinessType(s);
        paymentInfo.setInnerTxnType(s);
        paymentInfo.setAmount(l);
        paymentInfo.setTerminalNo(s);
        paymentInfo.setTerminalSeqNo(s);
        paymentInfo.setAcceptOrgCode(s);
        paymentInfo.setAcceptTxnSeqNo(s);
        paymentInfo.setAcceptOperatorNo(s);
        paymentInfo.setAcceptDate(s);
        paymentInfo.setAcceptTime(s);
        paymentInfo.setPayOrgCode(s);
        paymentInfo.setTxnType(TxnType.TXN_CONSUME);
        paymentInfo.setTxnDscpt(s);
        TInfoAccount account = new TInfoAccount();
        account.setAccountNo(s);
        account.setAccountName(s);
        account.setCustomerNo(s);
        account.setOpenDate(date);
        account.setCloseDate(date);
        account.setExpiredDate(date);
        account.setPayPasswd(s);
        account.setInitPasswd(s);
        account.setInitPasswdModified(s);
        account.setPasswdErrNum(l);
        account.setPasswdErrLockTime(date);
        account.setStatus(s);
        account.setCommStatus(s);
        account.setType(s);
        account.setGrade(s);
        account.setIsRealname(s);
        account.setApanage(s);
        account.setOrganizationCode(s);
        account.setAreaCode(s);
        account.setCityCode(s);
        account.setOpenChannel(s);
        account.setBalance(l);
        account.setLastDayBal(l);
        account.setLastMonthBal(l);
        account.setAvailableBalance(l);
        account.setUnavailableBalance(l);
        account.setWithdrawBalance(l);
        account.setFrozenAmount(l);
        account.setPreauthorizedAmt(l);
        account.setLastTxnDate(s);
        account.setDaySumConsAmt(l);
        account.setDaySumConsCnt(1);
        account.setDaySumOutAmt(l);
        account.setDaySumOutCnt(1);
        account.setDaySumInAmt(l);
        account.setDaySumInCnt(1);
        account.setDaySumCashAmt(l);
        account.setDaySumCashCnt(1);
        account.setDaySumDepositAmt(l);
        account.setDaySumDepositCnt(1);
        account.setMonthSumConsAmt(l);
        account.setMonthSumOutAmt(l);
        account.setMonthSumInAmt(l);
        account.setMonthSumCashAmt(l);
        account.setMonthSumChgAmt(l);
        account.setIsAllowedClose(s);
        account.setIsCloseRtnCash(s);
        account.setEncryptedMsg(s);
        account.setLastUpdateTime(date);
        account.setLastTxnTime(date);
        account.setRsvdAmt1(l);
        account.setRsvdAmt2(l);
        account.setRsvdText1(s);
        account.setRsvdText2(s);
        account.setMonthSumConsCnt(l);
        account.setMonthSumOutCnt(l);
        account.setMonthSumInCnt(l);
        account.setMonthSumCashCnt(l);
        account.setMonthSumChgCnt(l);
        account.setMasterAccountNo(s);
        account.setForbiddenTxn(s);
        account.setExtendCount(l);
        account.setForbiddenChannel(s);
        account.setCardNo(s);
        account.setCardType(s);
        account.setCardBindingMethod(s);
        TInfoOrg acceptOrg = new TInfoOrg();
        acceptOrg.setRecordNo(l);
        acceptOrg.setOrgCode(s);
        acceptOrg.setOrgType(s);
        acceptOrg.setSubType(s);
        acceptOrg.setOrgFname(s);
        acceptOrg.setOrgSname(s);
        acceptOrg.setIndustryType(s);
        acceptOrg.setAddress(s);
        acceptOrg.setZipCode(s);
        acceptOrg.setBusinessLicenseNo(s);
        acceptOrg.setOrganizationCode(s);
        acceptOrg.setLegalRepresentiveName(s);
        acceptOrg.setLinkmanName(s);
        acceptOrg.setLinkmanTelephone(s);
        acceptOrg.setLinkmanFax(s);
        acceptOrg.setLinkmanEmail(s);
        acceptOrg.setServiceLevel(s);
        acceptOrg.setRiskLevel(s);
        acceptOrg.setAllowTrans(s);
        acceptOrg.setOrgStatus(s);
        acceptOrg.setAreaCode(s);
        acceptOrg.setCityCode(s);
        acceptOrg.setUpOrgCode(s);
        acceptOrg.setSignOrgCode(s);
        acceptOrg.setClearingOrgCode(s);
        acceptOrg.setSettlementOrgCode(s);
        acceptOrg.setSettlementMode(s);
        acceptOrg.setIsRealClear(s);
        acceptOrg.setClearingDate(s);
        acceptOrg.setSettleDate(s);
        acceptOrg.setfLinkmanName(s);
        acceptOrg.setfLinkmanTelephone(s);
        acceptOrg.setfLinkmanFax(s);
        acceptOrg.setfLinkmanEmail(s);
        acceptOrg.setCreateUid(s);
        acceptOrg.setCreateTime(date);
        acceptOrg.setCheckFlag(s);
        acceptOrg.setCheckUid(s);
        acceptOrg.setCheckTime(date);
        acceptOrg.setLastModifyUid(s);
        acceptOrg.setLastModifyTime(date);
        acceptOrg.setSettlementMin1(l);
        acceptOrg.setSettlementMin2(l);
        acceptOrg.setSettlementMin3(l);
        acceptOrg.setSettlementMin4(l);
        acceptOrg.setSettlementMin5(l);
        acceptOrg.setChargeAccFlag(s);
        acceptOrg.setOrgKind(s);
        acceptOrg.setArchiveTime(date);
        acceptOrg.setArchiveFlag(s);
        acceptOrg.setlRecordNo(l);
        acceptOrg.setRemark(s);
        acceptOrg.setBlackLabel(s);
        acceptOrg.setSettleFlag(s);
        acceptOrg.setPayType(s);
        acceptOrg.setResvFld1(s);
        acceptOrg.setResvFld2(s);
        acceptOrg.setResvFld3(s);

        String cleaningTxnSeqNo = "ss";
        service.accounTxnInDb(paymentInfo,account,acceptOrg,cleaningTxnSeqNo);
    }

    @Test
    public void accountDecreaseAlterInDb(){
        String s = "s";
        Long l = 11L;
        Date date = new Date();
        PaymentInfo paymentInfo = new PaymentInfo();
        paymentInfo.setMerchantCode(s);
        paymentInfo.setSupplyOrgCode(s);
        paymentInfo.setChannel(s);
        paymentInfo.setBussinessType(s);
        paymentInfo.setInnerTxnType(s);
        paymentInfo.setAmount(l);
        paymentInfo.setTerminalNo(s);
        paymentInfo.setTerminalSeqNo(s);
        paymentInfo.setAcceptOrgCode(s);
        paymentInfo.setAcceptTxnSeqNo(s);
        paymentInfo.setAcceptOperatorNo(s);
        paymentInfo.setAcceptDate(s);
        paymentInfo.setAcceptTime(s);
        paymentInfo.setPayOrgCode(s);
        paymentInfo.setTxnType(TxnType.TXN_CONSUME);
        paymentInfo.setTxnDscpt(s);
        TInfoAccount account = new TInfoAccount();
        account.setAccountNo("00000003461815");
        account.setAccountName(s);
        account.setCustomerNo(s);
        account.setOpenDate(date);
        account.setCloseDate(date);
        account.setExpiredDate(date);
        account.setPayPasswd(s);
        account.setInitPasswd(s);
        account.setInitPasswdModified(s);
        account.setPasswdErrNum(l);
        account.setPasswdErrLockTime(date);
        account.setStatus(s);
        account.setCommStatus(s);
        account.setType(s);
        account.setGrade(s);
        account.setIsRealname(s);
        account.setApanage(s);
        account.setOrganizationCode(s);
        account.setAreaCode(s);
        account.setCityCode(s);
        account.setOpenChannel(s);
        account.setBalance(l);
        account.setLastDayBal(l);
        account.setLastMonthBal(l);
        account.setAvailableBalance(l);
        account.setUnavailableBalance(l);
        account.setWithdrawBalance(l);
        account.setFrozenAmount(l);
        account.setPreauthorizedAmt(l);
        account.setLastTxnDate("111111111111");
        account.setDaySumConsAmt(l);
        account.setDaySumConsCnt(1);
        account.setDaySumOutAmt(l);
        account.setDaySumOutCnt(1);
        account.setDaySumInAmt(l);
        account.setDaySumInCnt(1);
        account.setDaySumCashAmt(l);
        account.setDaySumCashCnt(1);
        account.setDaySumDepositAmt(l);
        account.setDaySumDepositCnt(1);
        account.setMonthSumConsAmt(l);
        account.setMonthSumOutAmt(l);
        account.setMonthSumInAmt(l);
        account.setMonthSumCashAmt(l);
        account.setMonthSumChgAmt(l);
        account.setIsAllowedClose(s);
        account.setIsCloseRtnCash(s);
        account.setEncryptedMsg(s);
        account.setLastUpdateTime(date);
        account.setLastTxnTime(date);
        account.setRsvdAmt1(l);
        account.setRsvdAmt2(l);
        account.setRsvdText1(s);
        account.setRsvdText2(s);
        account.setMonthSumConsCnt(l);
        account.setMonthSumOutCnt(l);
        account.setMonthSumInCnt(l);
        account.setMonthSumCashCnt(l);
        account.setMonthSumChgCnt(l);
        account.setMasterAccountNo(s);
        account.setForbiddenTxn(s);
        account.setExtendCount(l);
        account.setForbiddenChannel(s);
        account.setCardNo(s);
        account.setCardType(s);
        account.setCardBindingMethod(s);
        Long l1 = service.accountDecreaseAlterInDb(account,paymentInfo,null);
        System.out.println("---accountDecreaseAlterInDb---------------"+ l1);
    }

    @Test
    public void feeCatulatorInDb(){
        PaymentInfo paymentInfo = new PaymentInfo();
        TInfoAccount account = new TInfoAccount();
        TInfoCustomer tInfoCustomer = new TInfoCustomer();
        TInfoOrg acceptOrg = new TInfoOrg();
        TInfoOrg merchantOrg = new TInfoOrg();
        String txnSeqNo = "";
        TLogOnlinePayment l = service.feeCatulatorInDb(paymentInfo, account, tInfoCustomer, acceptOrg,merchantOrg, txnSeqNo);
        System.out.println("---feeCatulatorInDb---------------"+ l);
    }

    @Test
    public void cancelFeeCatulatorInDb(){
        String s = "s";
        Long l = 11L;
        Date date = new Date();
        TInfoCustomer tInfoCustomer = new TInfoCustomer();
        tInfoCustomer.setCustomerNo(s);
        tInfoCustomer.setUnifyId(s);
        tInfoCustomer.setIsRealname(s);
        tInfoCustomer.setName(s);
        tInfoCustomer.setIsRequestCertificate(s);
        tInfoCustomer.setRegisterType(s);
        tInfoCustomer.setMobileNo(s);
        tInfoCustomer.setEmailAddress(s);
        tInfoCustomer.setUserName(s);
        tInfoCustomer.setNickName(s);
        tInfoCustomer.setWebLoginPassword(s);
        tInfoCustomer.setIvrPassword(s);
        tInfoCustomer.setAccountQueryPassword(s);
        tInfoCustomer.setGender(s);
        tInfoCustomer.setIdentifyType(s);
        tInfoCustomer.setIdentifyNo(s);
        tInfoCustomer.setHomeTelephone(s);
        tInfoCustomer.setOfficeTelephone(s);
        tInfoCustomer.setOtherTelephone(s);
        tInfoCustomer.setApanage(s);
        tInfoCustomer.setAreaCode(s);
        tInfoCustomer.setCityCode(s);
        tInfoCustomer.setContactAddress(s);
        tInfoCustomer.setContactZipcode(s);
        tInfoCustomer.setOrganizationAddress(s);
        tInfoCustomer.setOrganizationZipcode(s);
        tInfoCustomer.setPwdErrCount(l);
        tInfoCustomer.setLockTimeLimit(date);
        tInfoCustomer.setOrganizationCode(s);
        tInfoCustomer.setQuestion(s);
        tInfoCustomer.setAnswer(s);
        tInfoCustomer.setActiveAddress(s);
        tInfoCustomer.setActiveCode(s);
        tInfoCustomer.setActiveStatus(s);
        tInfoCustomer.setRegisteDate(date);
        tInfoCustomer.setIsClosingAccount(s);
        tInfoCustomer.setRegisteOrgCode(s);
        tInfoCustomer.setRegisteUid(s);
        tInfoCustomer.setManager(s);
        tInfoCustomer.setLastSuccessLoginTime(date);
        tInfoCustomer.setLastSuccessLoginIp(s);
        tInfoCustomer.setLastFailLoginTime(date);
        tInfoCustomer.setLastFailLoginIp(s);
        tInfoCustomer.setLastUpdateTime(date);
        tInfoCustomer.setCustomerStatus(s);
        tInfoCustomer.setCloseTime(date);
        tInfoCustomer.setActiveTimeLimit(date);
        tInfoCustomer.setActiveTime(date);
        tInfoCustomer.setCustomerGrade(s);
        tInfoCustomer.setCustomerType(s);
        tInfoCustomer.setNationality(s);
        tInfoCustomer.setProfession(s);
        tInfoCustomer.setIdentifyExpiredDate(s);
        tInfoCustomer.setBlacklistFlag(s);

        PaymentInfo paymentInfo = new PaymentInfo();

        paymentInfo.setMerchantCode(s);
        paymentInfo.setSupplyOrgCode(s);
        paymentInfo.setChannel(s);
        paymentInfo.setBussinessType(s);
        paymentInfo.setInnerTxnType(s);
        paymentInfo.setAmount(l);
        paymentInfo.setTerminalNo(s);
        paymentInfo.setTerminalSeqNo(s);
        paymentInfo.setAcceptOrgCode(s);
        paymentInfo.setAcceptTxnSeqNo(s);
        paymentInfo.setAcceptOperatorNo(s);
        paymentInfo.setAcceptDate(s);
        paymentInfo.setAcceptTime(s);
        paymentInfo.setPayOrgCode(s);
        paymentInfo.setTxnType(TxnType.TXN_CONSUME);
        paymentInfo.setTxnDscpt(s);
        TInfoAccount account = new TInfoAccount();
        account.setAccountNo(s);
        account.setAccountName(s);
        account.setCustomerNo(s);
        account.setOpenDate(date);
        account.setCloseDate(date);
        account.setExpiredDate(date);
        account.setPayPasswd(s);
        account.setInitPasswd(s);
        account.setInitPasswdModified(s);
        account.setPasswdErrNum(l);
        account.setPasswdErrLockTime(date);
        account.setStatus(s);
        account.setCommStatus(s);
        account.setType(s);
        account.setGrade(s);
        account.setIsRealname(s);
        account.setApanage(s);
        account.setOrganizationCode(s);
        account.setAreaCode(s);
        account.setCityCode(s);
        account.setOpenChannel(s);
        account.setBalance(l);
        account.setLastDayBal(l);
        account.setLastMonthBal(l);
        account.setAvailableBalance(l);
        account.setUnavailableBalance(l);
        account.setWithdrawBalance(l);
        account.setFrozenAmount(l);
        account.setPreauthorizedAmt(l);
        account.setLastTxnDate(s);
        account.setDaySumConsAmt(l);
        account.setDaySumConsCnt(1);
        account.setDaySumOutAmt(l);
        account.setDaySumOutCnt(1);
        account.setDaySumInAmt(l);
        account.setDaySumInCnt(1);
        account.setDaySumCashAmt(l);
        account.setDaySumCashCnt(1);
        account.setDaySumDepositAmt(l);
        account.setDaySumDepositCnt(1);
        account.setMonthSumConsAmt(l);
        account.setMonthSumOutAmt(l);
        account.setMonthSumInAmt(l);
        account.setMonthSumCashAmt(l);
        account.setMonthSumChgAmt(l);
        account.setIsAllowedClose(s);
        account.setIsCloseRtnCash(s);
        account.setEncryptedMsg(s);
        account.setLastUpdateTime(date);
        account.setLastTxnTime(date);
        account.setRsvdAmt1(l);
        account.setRsvdAmt2(l);
        account.setRsvdText1(s);
        account.setRsvdText2(s);
        account.setMonthSumConsCnt(l);
        account.setMonthSumOutCnt(l);
        account.setMonthSumInCnt(l);
        account.setMonthSumCashCnt(l);
        account.setMonthSumChgCnt(l);
        account.setMasterAccountNo(s);
        account.setForbiddenTxn(s);
        account.setExtendCount(l);
        account.setForbiddenChannel(s);
        account.setCardNo(s);
        account.setCardType(s);
        account.setCardBindingMethod(s);
        TInfoOrg acceptOrg = new TInfoOrg();
        acceptOrg.setRecordNo(l);
        acceptOrg.setOrgCode(s);
        acceptOrg.setOrgType(s);
        acceptOrg.setSubType(s);
        acceptOrg.setOrgFname(s);
        acceptOrg.setOrgSname(s);
        acceptOrg.setIndustryType(s);
        acceptOrg.setAddress(s);
        acceptOrg.setZipCode(s);
        acceptOrg.setBusinessLicenseNo(s);
        acceptOrg.setOrganizationCode(s);
        acceptOrg.setLegalRepresentiveName(s);
        acceptOrg.setLinkmanName(s);
        acceptOrg.setLinkmanTelephone(s);
        acceptOrg.setLinkmanFax(s);
        acceptOrg.setLinkmanEmail(s);
        acceptOrg.setServiceLevel(s);
        acceptOrg.setRiskLevel(s);
        acceptOrg.setAllowTrans(s);
        acceptOrg.setOrgStatus(s);
        acceptOrg.setAreaCode(s);
        acceptOrg.setCityCode(s);
        acceptOrg.setUpOrgCode(s);
        acceptOrg.setSignOrgCode(s);
        acceptOrg.setClearingOrgCode(s);
        acceptOrg.setSettlementOrgCode(s);
        acceptOrg.setSettlementMode(s);
        acceptOrg.setIsRealClear(s);
        acceptOrg.setClearingDate(s);
        acceptOrg.setSettleDate(s);
        acceptOrg.setfLinkmanName(s);
        acceptOrg.setfLinkmanTelephone(s);
        acceptOrg.setfLinkmanFax(s);
        acceptOrg.setfLinkmanEmail(s);
        acceptOrg.setCreateUid(s);
        acceptOrg.setCreateTime(date);
        acceptOrg.setCheckFlag(s);
        acceptOrg.setCheckUid(s);
        acceptOrg.setCheckTime(date);
        acceptOrg.setLastModifyUid(s);
        acceptOrg.setLastModifyTime(date);
        acceptOrg.setSettlementMin1(l);
        acceptOrg.setSettlementMin2(l);
        acceptOrg.setSettlementMin3(l);
        acceptOrg.setSettlementMin4(l);
        acceptOrg.setSettlementMin5(l);
        acceptOrg.setChargeAccFlag(s);
        acceptOrg.setOrgKind(s);
        acceptOrg.setArchiveTime(date);
        acceptOrg.setArchiveFlag(s);
        acceptOrg.setlRecordNo(l);
        acceptOrg.setRemark(s);
        acceptOrg.setBlackLabel(s);
        acceptOrg.setSettleFlag(s);
        acceptOrg.setPayType(s);
        acceptOrg.setResvFld1(s);
        acceptOrg.setResvFld2(s);
        acceptOrg.setResvFld3(s);

        TInfoOrg merchantOrg = new TInfoOrg();

        merchantOrg.setRecordNo(l);
        merchantOrg.setOrgCode(s);
        merchantOrg.setOrgType(s);
        merchantOrg.setSubType(s);
        merchantOrg.setOrgFname(s);
        merchantOrg.setOrgSname(s);
        merchantOrg.setIndustryType(s);
        merchantOrg.setAddress(s);
        merchantOrg.setZipCode(s);
        merchantOrg.setBusinessLicenseNo(s);
        merchantOrg.setOrganizationCode(s);
        merchantOrg.setLegalRepresentiveName(s);
        merchantOrg.setLinkmanName(s);
        merchantOrg.setLinkmanTelephone(s);
        merchantOrg.setLinkmanFax(s);
        merchantOrg.setLinkmanEmail(s);
        merchantOrg.setServiceLevel(s);
        merchantOrg.setRiskLevel(s);
        merchantOrg.setAllowTrans(s);
        merchantOrg.setOrgStatus(s);
        merchantOrg.setAreaCode(s);
        merchantOrg.setCityCode(s);
        merchantOrg.setUpOrgCode(s);
        merchantOrg.setSignOrgCode(s);
        merchantOrg.setClearingOrgCode(s);
        merchantOrg.setSettlementOrgCode(s);
        merchantOrg.setSettlementMode(s);
        merchantOrg.setIsRealClear(s);
        merchantOrg.setClearingDate(s);
        merchantOrg.setSettleDate(s);
        merchantOrg.setfLinkmanName(s);
        merchantOrg.setfLinkmanTelephone(s);
        merchantOrg.setfLinkmanFax(s);
        merchantOrg.setfLinkmanEmail(s);
        merchantOrg.setCreateUid(s);
        merchantOrg.setCreateTime(date);
        merchantOrg.setCheckFlag(s);
        merchantOrg.setCheckUid(s);
        merchantOrg.setCheckTime(date);
        merchantOrg.setLastModifyUid(s);
        merchantOrg.setLastModifyTime(date);
        merchantOrg.setSettlementMin1(l);
        merchantOrg.setSettlementMin2(l);
        merchantOrg.setSettlementMin3(l);
        merchantOrg.setSettlementMin4(l);
        merchantOrg.setSettlementMin5(l);
        merchantOrg.setChargeAccFlag(s);
        merchantOrg.setOrgKind(s);
        merchantOrg.setArchiveTime(date);
        merchantOrg.setArchiveFlag(s);
        merchantOrg.setlRecordNo(l);
        merchantOrg.setRemark(s);
        merchantOrg.setBlackLabel(s);
        merchantOrg.setSettleFlag(s);
        merchantOrg.setPayType(s);
        merchantOrg.setResvFld1(s);
        merchantOrg.setResvFld2(s);
        merchantOrg.setResvFld3(s);
        String canceledTxnSeqNo = "";
        TLogOnlinePayment l1 = service.cancelFeeCatulatorInDb(paymentInfo, account, tInfoCustomer, acceptOrg, merchantOrg, canceledTxnSeqNo);
        System.out.println("---cancelFeeCatulatorInDb---------------"+ l1);
    }

    @Test
    public void accountIncreaseAlterInDb(){
        String s = "";
        Long l = 11L;
        Date date = new Date();
        PaymentInfo paymentInfo = new PaymentInfo();
        paymentInfo.setMerchantCode(s);
        paymentInfo.setSupplyOrgCode(s);
        paymentInfo.setChannel(s);
        paymentInfo.setBussinessType(s);
        paymentInfo.setInnerTxnType(s);
        paymentInfo.setAmount(l);
        paymentInfo.setTerminalNo(s);
        paymentInfo.setTerminalSeqNo(s);
        paymentInfo.setAcceptOrgCode(s);
        paymentInfo.setAcceptTxnSeqNo(s);
        paymentInfo.setAcceptOperatorNo(s);
        paymentInfo.setAcceptDate(s);
        paymentInfo.setAcceptTime(s);
        paymentInfo.setPayOrgCode(s);
        paymentInfo.setTxnType(TxnType.TXN_CONSUME);
        paymentInfo.setTxnDscpt(s);
        TInfoAccount account = new TInfoAccount();
        account.setAccountNo("11111111111");
        account.setAccountName(s);
        account.setCustomerNo(s);
        account.setOpenDate(date);
        account.setCloseDate(date);
        account.setExpiredDate(date);
        account.setPayPasswd(s);
        account.setInitPasswd(s);
        account.setInitPasswdModified(s);
        account.setPasswdErrNum(l);
        account.setPasswdErrLockTime(date);
        account.setStatus(s);
        account.setCommStatus(s);
        account.setType(s);
        account.setGrade(s);
        account.setIsRealname(s);
        account.setApanage(s);
        account.setOrganizationCode(s);
        account.setAreaCode(s);
        account.setCityCode(s);
        account.setOpenChannel(s);
        account.setBalance(l);
        account.setLastDayBal(l);
        account.setLastMonthBal(l);
        account.setAvailableBalance(l);
        account.setUnavailableBalance(l);
        account.setWithdrawBalance(l);
        account.setFrozenAmount(l);
        account.setPreauthorizedAmt(l);
        account.setLastTxnDate("111111111111");
        account.setDaySumConsAmt(l);
        account.setDaySumConsCnt(1);
        account.setDaySumOutAmt(l);
        account.setDaySumOutCnt(1);
        account.setDaySumInAmt(l);
        account.setDaySumInCnt(1);
        account.setDaySumCashAmt(l);
        account.setDaySumCashCnt(1);
        account.setDaySumDepositAmt(l);
        account.setDaySumDepositCnt(1);
        account.setMonthSumConsAmt(l);
        account.setMonthSumOutAmt(l);
        account.setMonthSumInAmt(l);
        account.setMonthSumCashAmt(l);
        account.setMonthSumChgAmt(l);
        account.setIsAllowedClose(s);
        account.setIsCloseRtnCash(s);
        account.setEncryptedMsg(s);
        account.setLastUpdateTime(date);
        account.setLastTxnTime(date);
        account.setRsvdAmt1(l);
        account.setRsvdAmt2(l);
        account.setRsvdText1(s);
        account.setRsvdText2(s);
        account.setMonthSumConsCnt(l);
        account.setMonthSumOutCnt(l);
        account.setMonthSumInCnt(l);
        account.setMonthSumCashCnt(l);
        account.setMonthSumChgCnt(l);
        account.setMasterAccountNo(s);
        account.setForbiddenTxn(s);
        account.setExtendCount(l);
        account.setForbiddenChannel(s);
        account.setCardNo(s);
        account.setCardType(s);
        account.setCardBindingMethod(s);
        Long l1 = service.accountIncreaseAlterInDb(account, paymentInfo, null,null);
        System.out.println("---accountIncreaseAlterInDb---------------"+ l1);
    }

    /**
     * 这个方法不测了，谁有时间谁测吧。
     */
    @Test
    public void cancelOldLogOnlinePayment(){
        String cancelTxnSeqNo = "";
        String s = "";
        Long l = 11L;
        Date date = new Date();
        PaymentInfo paymentInfo = new PaymentInfo();
        paymentInfo.setMerchantCode(s);
        paymentInfo.setSupplyOrgCode(s);
        paymentInfo.setChannel(s);
        paymentInfo.setBussinessType(s);
        paymentInfo.setInnerTxnType(s);
        paymentInfo.setAmount(l);
        paymentInfo.setTerminalNo(s);
        paymentInfo.setTerminalSeqNo(s);
        paymentInfo.setAcceptOrgCode(s);
        paymentInfo.setAcceptTxnSeqNo(s);
        paymentInfo.setAcceptOperatorNo(s);
        paymentInfo.setAcceptDate(s);
        paymentInfo.setAcceptTime(s);
        paymentInfo.setPayOrgCode(s);
        paymentInfo.setTxnType(TxnType.TXN_CONSUME);
        paymentInfo.setTxnDscpt(s);
        PaymentInfo oldPaymentInfo = new PaymentInfo();
        oldPaymentInfo.setMerchantCode(s);
        oldPaymentInfo.setSupplyOrgCode(s);
        oldPaymentInfo.setChannel(s);
        oldPaymentInfo.setBussinessType(s);
        oldPaymentInfo.setInnerTxnType(s);
        oldPaymentInfo.setAmount(l);
        oldPaymentInfo.setTerminalNo(s);
        oldPaymentInfo.setTerminalSeqNo(s);
        oldPaymentInfo.setAcceptOrgCode(s);
        oldPaymentInfo.setAcceptTxnSeqNo(s);
        oldPaymentInfo.setAcceptOperatorNo(s);
        oldPaymentInfo.setAcceptDate(s);
        oldPaymentInfo.setAcceptTime(s);
        oldPaymentInfo.setPayOrgCode(s);
        oldPaymentInfo.setTxnType(TxnType.TXN_CONSUME);
        oldPaymentInfo.setTxnDscpt(s);
        TInfoAccount account = new TInfoAccount();
        account.setAccountNo("111111111111");
        account.setAccountName(s);
        account.setCustomerNo(s);
        account.setOpenDate(date);
        account.setCloseDate(date);
        account.setExpiredDate(date);
        account.setPayPasswd(s);
        account.setInitPasswd(s);
        account.setInitPasswdModified(s);
        account.setPasswdErrNum(l);
        account.setPasswdErrLockTime(date);
        account.setStatus(s);
        account.setCommStatus(s);
        account.setType(s);
        account.setGrade(s);
        account.setIsRealname(s);
        account.setApanage(s);
        account.setOrganizationCode(s);
        account.setAreaCode(s);
        account.setCityCode(s);
        account.setOpenChannel(s);
        account.setBalance(l);
        account.setLastDayBal(l);
        account.setLastMonthBal(l);
        account.setAvailableBalance(l);
        account.setUnavailableBalance(l);
        account.setWithdrawBalance(l);
        account.setFrozenAmount(l);
        account.setPreauthorizedAmt(l);
        account.setLastTxnDate("111111111111");
        account.setDaySumConsAmt(l);
        account.setDaySumConsCnt(1);
        account.setDaySumOutAmt(l);
        account.setDaySumOutCnt(1);
        account.setDaySumInAmt(l);
        account.setDaySumInCnt(1);
        account.setDaySumCashAmt(l);
        account.setDaySumCashCnt(1);
        account.setDaySumDepositAmt(l);
        account.setDaySumDepositCnt(1);
        account.setMonthSumConsAmt(l);
        account.setMonthSumOutAmt(l);
        account.setMonthSumInAmt(l);
        account.setMonthSumCashAmt(l);
        account.setMonthSumChgAmt(l);
        account.setIsAllowedClose(s);
        account.setIsCloseRtnCash(s);
        account.setEncryptedMsg(s);
        account.setLastUpdateTime(date);
        account.setLastTxnTime(date);
        account.setRsvdAmt1(l);
        account.setRsvdAmt2(l);
        account.setRsvdText1(s);
        account.setRsvdText2(s);
        account.setMonthSumConsCnt(l);
        account.setMonthSumOutCnt(l);
        account.setMonthSumInCnt(l);
        account.setMonthSumCashCnt(l);
        account.setMonthSumChgCnt(l);
        account.setMasterAccountNo(s);
        account.setForbiddenTxn(s);
        account.setExtendCount(l);
        account.setForbiddenChannel(s);
        account.setCardNo(s);
        account.setCardType(s);
        account.setCardBindingMethod(s);
        TLogOnlinePayment tLogOnlinePayment = service.cancelOldLogOnlinePayment(account, paymentInfo, oldPaymentInfo,cancelTxnSeqNo);
        System.out.println("cancelOldLogOnlinePayment=============" + tLogOnlinePayment.getAccountNo());
    }

    @Test
    public void rollbackOldLogOnlinePayment(){
        String s = "";
        Long l = 11L;
        Date date = new Date();
        TInfoCustomer tInfoCustomer = new TInfoCustomer();
        tInfoCustomer.setCustomerNo(s);
        tInfoCustomer.setUnifyId(s);
        tInfoCustomer.setIsRealname(s);
        tInfoCustomer.setName(s);
        tInfoCustomer.setIsRequestCertificate(s);
        tInfoCustomer.setRegisterType(s);
        tInfoCustomer.setMobileNo(s);
        tInfoCustomer.setEmailAddress(s);
        tInfoCustomer.setUserName(s);
        tInfoCustomer.setNickName(s);
        tInfoCustomer.setWebLoginPassword(s);
        tInfoCustomer.setIvrPassword(s);
        tInfoCustomer.setAccountQueryPassword(s);
        tInfoCustomer.setGender(s);
        tInfoCustomer.setIdentifyType(s);
        tInfoCustomer.setIdentifyNo(s);
        tInfoCustomer.setHomeTelephone(s);
        tInfoCustomer.setOfficeTelephone(s);
        tInfoCustomer.setOtherTelephone(s);
        tInfoCustomer.setApanage(s);
        tInfoCustomer.setAreaCode(s);
        tInfoCustomer.setCityCode(s);
        tInfoCustomer.setContactAddress(s);
        tInfoCustomer.setContactZipcode(s);
        tInfoCustomer.setOrganizationAddress(s);
        tInfoCustomer.setOrganizationZipcode(s);
        tInfoCustomer.setPwdErrCount(l);
        tInfoCustomer.setLockTimeLimit(date);
        tInfoCustomer.setOrganizationCode(s);
        tInfoCustomer.setQuestion(s);
        tInfoCustomer.setAnswer(s);
        tInfoCustomer.setActiveAddress(s);
        tInfoCustomer.setActiveCode(s);
        tInfoCustomer.setActiveStatus(s);
        tInfoCustomer.setRegisteDate(date);
        tInfoCustomer.setIsClosingAccount(s);
        tInfoCustomer.setRegisteOrgCode(s);
        tInfoCustomer.setRegisteUid(s);
        tInfoCustomer.setManager(s);
        tInfoCustomer.setLastSuccessLoginTime(date);
        tInfoCustomer.setLastSuccessLoginIp(s);
        tInfoCustomer.setLastFailLoginTime(date);
        tInfoCustomer.setLastFailLoginIp(s);
        tInfoCustomer.setLastUpdateTime(date);
        tInfoCustomer.setCustomerStatus(s);
        tInfoCustomer.setCloseTime(date);
        tInfoCustomer.setActiveTimeLimit(date);
        tInfoCustomer.setActiveTime(date);
        tInfoCustomer.setCustomerGrade(s);
        tInfoCustomer.setCustomerType(s);
        tInfoCustomer.setNationality(s);
        tInfoCustomer.setProfession(s);
        tInfoCustomer.setIdentifyExpiredDate(s);
        tInfoCustomer.setBlacklistFlag(s);

        TInfoOrg supplyOrg = new TInfoOrg();
        TInfoOrg acceptOrg = new TInfoOrg();
        acceptOrg.setRecordNo(l);
        acceptOrg.setOrgCode(s);
        acceptOrg.setOrgType(s);
        acceptOrg.setSubType(s);
        acceptOrg.setOrgFname(s);
        acceptOrg.setOrgSname(s);
        acceptOrg.setIndustryType(s);
        acceptOrg.setAddress(s);
        acceptOrg.setZipCode(s);
        acceptOrg.setBusinessLicenseNo(s);
        acceptOrg.setOrganizationCode(s);
        acceptOrg.setLegalRepresentiveName(s);
        acceptOrg.setLinkmanName(s);
        acceptOrg.setLinkmanTelephone(s);
        acceptOrg.setLinkmanFax(s);
        acceptOrg.setLinkmanEmail(s);
        acceptOrg.setServiceLevel(s);
        acceptOrg.setRiskLevel(s);
        acceptOrg.setAllowTrans(s);
        acceptOrg.setOrgStatus(s);
        acceptOrg.setAreaCode(s);
        acceptOrg.setCityCode(s);
        acceptOrg.setUpOrgCode(s);
        acceptOrg.setSignOrgCode(s);
        acceptOrg.setClearingOrgCode(s);
        acceptOrg.setSettlementOrgCode(s);
        acceptOrg.setSettlementMode(s);
        acceptOrg.setIsRealClear(s);
        acceptOrg.setClearingDate(s);
        acceptOrg.setSettleDate(s);
        acceptOrg.setfLinkmanName(s);
        acceptOrg.setfLinkmanTelephone(s);
        acceptOrg.setfLinkmanFax(s);
        acceptOrg.setfLinkmanEmail(s);
        acceptOrg.setCreateUid(s);
        acceptOrg.setCreateTime(date);
        acceptOrg.setCheckFlag(s);
        acceptOrg.setCheckUid(s);
        acceptOrg.setCheckTime(date);
        acceptOrg.setLastModifyUid(s);
        acceptOrg.setLastModifyTime(date);
        acceptOrg.setSettlementMin1(l);
        acceptOrg.setSettlementMin2(l);
        acceptOrg.setSettlementMin3(l);
        acceptOrg.setSettlementMin4(l);
        acceptOrg.setSettlementMin5(l);
        acceptOrg.setChargeAccFlag(s);
        acceptOrg.setOrgKind(s);
        acceptOrg.setArchiveTime(date);
        acceptOrg.setArchiveFlag(s);
        acceptOrg.setlRecordNo(l);
        acceptOrg.setRemark(s);
        acceptOrg.setBlackLabel(s);
        acceptOrg.setSettleFlag(s);
        acceptOrg.setPayType(s);
        acceptOrg.setResvFld1(s);
        acceptOrg.setResvFld2(s);
        acceptOrg.setResvFld3(s);
        supplyOrg =  acceptOrg;

        PaymentInfo paymentInfo = new PaymentInfo();

        PaymentInfo oldPaymentInfo = new PaymentInfo();
        oldPaymentInfo.setMerchantCode(s);
        oldPaymentInfo.setSupplyOrgCode(s);
        oldPaymentInfo.setChannel(s);
        oldPaymentInfo.setBussinessType(s);
        oldPaymentInfo.setInnerTxnType("134020");
        oldPaymentInfo.setAmount(l);
        oldPaymentInfo.setTerminalNo(s);
        oldPaymentInfo.setTerminalSeqNo(s);
        oldPaymentInfo.setAcceptOrgCode(s);
        oldPaymentInfo.setAcceptTxnSeqNo(s);
        oldPaymentInfo.setAcceptOperatorNo(s);
        oldPaymentInfo.setAcceptDate(s);
        oldPaymentInfo.setAcceptTime(s);
        oldPaymentInfo.setPayOrgCode(s);
        oldPaymentInfo.setTxnType(TxnType.TXN_CONSUME);
        oldPaymentInfo.setTxnDscpt(s);

        paymentInfo = oldPaymentInfo;
        TInfoAccount account = new TInfoAccount();
        account.setAccountNo("111111111111");
        account.setAccountName(s);
        account.setCustomerNo(s);
        account.setOpenDate(date);
        account.setCloseDate(date);
        account.setExpiredDate(date);
        account.setPayPasswd(s);
        account.setInitPasswd(s);
        account.setInitPasswdModified(s);
        account.setPasswdErrNum(l);
        account.setPasswdErrLockTime(date);
        account.setStatus(s);
        account.setCommStatus(s);
        account.setType(s);
        account.setGrade(s);
        account.setIsRealname(s);
        account.setApanage(s);
        account.setOrganizationCode(s);
        account.setAreaCode(s);
        account.setCityCode(s);
        account.setOpenChannel(s);
        account.setBalance(l);
        account.setLastDayBal(l);
        account.setLastMonthBal(l);
        account.setAvailableBalance(l);
        account.setUnavailableBalance(l);
        account.setWithdrawBalance(l);
        account.setFrozenAmount(l);
        account.setPreauthorizedAmt(l);
        account.setLastTxnDate("111111111111");
        account.setDaySumConsAmt(l);
        account.setDaySumConsCnt(1);
        account.setDaySumOutAmt(l);
        account.setDaySumOutCnt(1);
        account.setDaySumInAmt(l);
        account.setDaySumInCnt(1);
        account.setDaySumCashAmt(l);
        account.setDaySumCashCnt(1);
        account.setDaySumDepositAmt(l);
        account.setDaySumDepositCnt(1);
        account.setMonthSumConsAmt(l);
        account.setMonthSumOutAmt(l);
        account.setMonthSumInAmt(l);
        account.setMonthSumCashAmt(l);
        account.setMonthSumChgAmt(l);
        account.setIsAllowedClose(s);
        account.setIsCloseRtnCash(s);
        account.setEncryptedMsg(s);
        account.setLastUpdateTime(date);
        account.setLastTxnTime(date);
        account.setRsvdAmt1(l);
        account.setRsvdAmt2(l);
        account.setRsvdText1(s);
        account.setRsvdText2(s);
        account.setMonthSumConsCnt(l);
        account.setMonthSumOutCnt(l);
        account.setMonthSumInCnt(l);
        account.setMonthSumCashCnt(l);
        account.setMonthSumChgCnt(l);
        account.setMasterAccountNo(s);
        account.setForbiddenTxn(s);
        account.setExtendCount(l);
        account.setForbiddenChannel(s);
        account.setCardNo(s);
        account.setCardType(s);
        account.setCardBindingMethod(s);
        String oldOnlineTxnSeqNo = "";
        String isClearing = "";
        TxnResultObject txnResultObject = new TxnResultObject();
        TLogOnlinePayment tLogOnlinePayment = service.rollbackOldLogOnlinePayment(supplyOrg, acceptOrg, paymentInfo, oldPaymentInfo, tInfoCustomer, account, oldOnlineTxnSeqNo,oldOnlineTxnSeqNo , txnResultObject);
        System.out.println("rollbackOldLogOnlinePayment============="+tLogOnlinePayment.getAccountNo());
    }

    @Test
    public void cancelOldLogAccountPayment(){
        String cancelOnlinePaymentTxnSeqNo = "00000000000003468619";
        TxnForm txnForm = TxnForm.TXN_LABL_ONLINE;

        service.cancelOldLogAccountPayment(cancelOnlinePaymentTxnSeqNo, txnForm);
    }

    @Test
    public void rollbackOldLogAccountPayment(){
        String rollbackOnlinePaymentTxnSeqNo = "00000000000003468619";
        TxnForm txnForm = TxnForm.TXN_LABL_OFFLINE;
        service.rollbackOldLogAccountPayment(rollbackOnlinePaymentTxnSeqNo, txnForm);
    }
}
